# Site settings
title: Yasmin Mosbah
name: Yasmin Mosbah

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Linkedin
   url: https://www.linkedin.com/in/ymosbah
 - title: GitHub
   url: https://github.com/yasmin-mosbah
 - title : Curriculum Vitae
   url : CV_PDF.pdf
#  - title: Kaggle
#    url: https://www.kaggle.com/yasminmosbah

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - CouchBase
 - MongoDB
 - FireBase
 - PostGreSQL
 - Oracle
 - Java
 - Android
 - Flutter
 - VBA
 - JavaScript
 - VueJs
 - Angular
 - SQL
 - PLSQL
 - noSQL

interests:
 - Adobe Photoshop
 - Adobe XD
 - Adobe Premiere Pro
 - Adobe Illustrator
 - Reading
 - Writing
 - Drawing
 - Riddle
 - BioChemistry

# #Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

# #Work experience is required
# roles:
#  - title: Data Scientist
#    start: 2020
#    end: 2021
#    employer: Enedis
#    description:  • Project management </br> • Automation of data retrieval from over 30 different sources </br> • Analysis and visualization of data with PowerBi
#  - title: Data Analyst
#    start: 2020
#    end: 2020
#    employer: Maison des Sciences de l’Homme et de la Société
#    description:  •  Statistical and forecasting studies on the impact of AirBnB on the region </br> • Processing and analysis of a very large amount of date
#  - title: Android Sotware Developer
#    start: 2019
#    end: 2019
#    employer: TokiDev
#    description: • Design and development of a mobile application </br> • Storage of semi-structured data from crowdsourcing </br> • Visualization of data on a map on mobile

# #Education is required
# # education:
# #  - title: Master's Degree 2
# #    start: 2008
# #    end: 2012
# #    subject: Applied Artificial Intelligence
# #    school: University of Cote d'Azur
# #  - title: Master's Degree 1
# #    start: 2008
# #    end: 2012
# #    subject: MIAGE (Computer Methods Applied to Business Management)
# #    school: University of Cote d'Azur
# #  - title: Bachelor's Degree 3
# #    start: 2008
# #    end: 2012
# #    subject: MIAGE (Computer Methods Applied to Business Management)
# #    school: University of Cote d'Azur
# #  - title: Bachelor's Degree 1 & 2
# #    start: 2008
# #    end: 2012
# #    subject: MASS (Mathematics Applied to Social Sciences)
# #    school: University of Cote d'Azur

# education:
#  - title: Data Scientist
#    start: 2020
#    end: 2021
#    employer: Enedis
#    description:  • Project management </br> • Automation of data retrieval from over 30 different sources </br> • Analysis and visualization of data with PowerBi
#  - title: Data Analyst
#    start: 2020
#    end: 2020
#    employer: Maison des Sciences de l’Homme et de la Société
#    description:  •  Statistical and forecasting studies on the impact of AirBnB on the region </br> • Processing and analysis of a very large amount of date
#  - title: Android Sotware Developer
#    start: 2019
#    end: 2019
#    employer: TokiDev
#    description: • Design and development of a mobile application </br> • Storage of semi-structured data from crowdsourcing </br> • Visualization of data on a map on mobile
#  - title: Data Scientist
#    start: 2020
#    end: 2021
#    employer: Enedis
#    description:  • Project management </br> • Automation of data retrieval from over 30 different sources </br> • Analysis and visualization of data with PowerBi
#  - title: Data Analyst
#    start: 2020
#    end: 2020
#    employer: Maison des Sciences de l’Homme et de la Société
#    description:  •  Statistical and forecasting studies on the impact of AirBnB on the region </br> • Processing and analysis of a very large amount of date
#  - title: Android Sotware Developer
#    start: 2019
#    end: 2019
#    employer: TokiDev
#    description: • Design and development of a mobile application </br> • Storage of semi-structured data from crowdsourcing </br> • Visualization of data on a map on mobile

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/de24f806f5b2d5b0539496491acbe8f9
   courses:
    - title: Machine Learning by Stanford University
      link: https://www.coursera.org/learn/machine-learning
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/ml/large-icon.png?auto=format%2Ccompress&dpr=1
      date: September 26, 2022
    # - title: Algorithms Design and Analysis, Part 1
    #   link: https://www.coursera.org/specializations/algorithms
    #   optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
    #   date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - Yasmin-Mosbah/modelisation-de-l-incertitude
 - Yasmin-Mosbah/evolutionary-algorithms
 - Yasmin-Mosbah/Agent-conversationnel
 - Yasmin-Mosbah/Implementation-ML-with-cuda
 - Yasmin-Mosbah/NPL-algorithme-d-analyse-de-sentiment-base-sur-les-aspects
 - Yasmin-Mosbah/NLP-algorithme-de-recherche-d-informations
 - Yasmin-Mosbah/NLP-systeme-de-questions-reponses
 - Yasmin-Mosbah/miaged-flutterApp
 - Yasmin-Mosbah/angular_projet
 - Neyran/Projet-Miage-Js
 - RemiFELIN/Projet-R-Gun-violence-data

# #Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png


intro: |
  I am a junior data scientist fresh out of school. I have a master's degree in Applied Artificial Intelligence, obtained at the Université Code d'Azur in France. Let's stop talking about studies and work. 
  I recently bought an electric bass in order to become a great rockstar. I also spend a lot of time drawing, or making creations on the multitudes of adobes applications.  I don't even talk about my passion for writing and reading.
  Life is definitely too short to explore all the beautiful things it has to offer. 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
#    <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries-such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>-as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#    <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4-Spring Boot-JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#    <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#    <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up-configuring and running applications using a range of AWS offerings-including EC2-RDS-S3-Cogito-<a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#    <strong>Web Development</strong>: Through building web applications-I have also worked with various client side technology-having used jQuery-Bootstrap-LESS-SASS-Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework-and extending them)<br/><br/>
#    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN-Git-Maven-Gradle-Sonar-Jenkins-TeamCity-etc. I have experience with an array of testing tools and technologies.<br/><br/>
#    I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time-including Android-a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#    As part of Nerdability-I created-and am now primary contributor to-two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>-which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#    I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
